version: "3"
services:
  chrome_video:
    image: selenium/video:ffmpeg-6.0-20231110
    volumes:
      - /home/lvuhoang/Documents/Video_Selenium_Grid:/videos
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4
